### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Rahulshah192006** [its-ag/discord-rpc#2]
Traceback (most recent call last):
  File "/home/rahul/discord-rpc/./start", line 11, in <module>
    gi.require_version('Playerctl', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Playerctl not available

**Comment by Rahulshah192006** [comment]
Bro Do something @its-ag
